POPSIZE: 5 
GENERATIONS: 50
ELITISM: 1
PROB_CROSSOVER: 0.9
PROB_MUTATION: 0.15
TSIZE: 5
GRAMMAR: 'grammars/dynamic_grammar.txt'
EXPERIMENT_NAME: "results/example"
RUN: 1
INCLUDE_GENOTYPE: True
SAVE_STEP: 1
VERBOSE: True
MIN_TREE_DEPTH: 6
MAX_TREE_DEPTH: 17
MODEL: 'models/mnist_model.h5'
VALIDATION_SIZE: 3500
TEST_SIZE: 3500
BATCH_SIZE: 1000
EPOCHS: 100
PREPOPULATE: False
