POPSIZE: 10 
GENERATIONS: 500
ELITISM: 0                   # number of individuals that survive
PROB_CROSSOVER: 0.9
PROB_MUTATION: 0.15
TSIZE: 3
GRAMMAR: 'grammars/adaptive_autolr_grammar.txt'
EXPERIMENT_NAME: 'dumps/adam_loose'
RUN: 2
INCLUDE_GENOTYPE: True
SAVE_STEP: 1
VERBOSE: True
MIN_TREE_DEPTH: 6
MAX_TREE_DEPTH: 17
MODEL: 'models/mnist_model.h5'
VALIDATION_SIZE: 3500
TEST_SIZE: 3500
BATCH_SIZE: 1000
EPOCHS: 10000
PREPOPULATE: True
PROTECT: False
GENES: 'adam'
PATIENCE: 5