RUN: 1
EXPERIMENT_NAME: 'dumps/base'
GRAMMAR: 'grammars/basic_optimizer.txt'
MIN_TREE_DEPTH: 6
MAX_TREE_DEPTH: 17
POPSIZE: 5
GENERATIONS: 1500
ELITISM: 1  
TSIZE: 5
PROB_CROSSOVER: 0.9
EPOCHS: 10000
MODEL: 'models/mnist_model.h5'
VALIDATION_SIZE: 3500
FITNESS_SIZE: 55000
BATCH_SIZE: 1000
PROB_MUTATION: 0.15