POPSIZE: 5 
GENERATIONS: 50
ELITISM: 1                    # number of individuals that survive
PROB_CROSSOVER: 0.9
PROB_MUTATION: 0.15
TSIZE: 5
GRAMMAR: 'grammars/grammar_proposal.txt'
EXPERIMENT_NAME: 'dumps/Test'
RUN: 1
INCLUDE_GENOTYPE: True
SAVE_STEP: 1
VERBOSE: True
MIN_TREE_DEPTH: 6
MAX_TREE_DEPTH: 17